"""added user, property and relationship tables

Revision ID: 49ca2f0d3e7e
Revises: 
Create Date: 2025-12-15 20:09:06.198268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ca2f0d3e7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street_address', 'city', 'state', 'postal_code', name='uq_property_address')
    )
    op.create_index('ix_properties_city_state', 'properties', ['city', 'state'], unique=False)
    op.create_index('ix_properties_county_state', 'properties', ['county', 'state'], unique=False)
    op.create_index('ix_properties_formatted_address', 'properties', ['formatted_address'], unique=False)
    op.create_index('ix_properties_postal_code', 'properties', ['postal_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('property_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', 'role', name='uq_property_user')
    )
    op.create_index('ix_property_users_active_only', 'property_users', ['user_id', 'property_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_property_users_property_id', 'property_users', ['property_id'], unique=False)
    op.create_index('ix_property_users_user_id', 'property_users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_property_users_user_id', table_name='property_users')
    op.drop_index('ix_property_users_property_id', table_name='property_users')
    op.drop_index('ix_property_users_active_only', table_name='property_users', postgresql_where=sa.text('is_active = true'))
    op.drop_table('property_users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_properties_postal_code', table_name='properties')
    op.drop_index('ix_properties_formatted_address', table_name='properties')
    op.drop_index('ix_properties_county_state', table_name='properties')
    op.drop_index('ix_properties_city_state', table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
